print('Enter your surname')
surname = input()
print('Enter your name')
name = input()
print('Individual horoscope for ' + name + ' ' + surname + '')
print('What is your favorite animal?')
animal = input()
print('In your previous life you were ' + animal + '')
print('What is your zodiac?')
zodiac = input()
print('Your zodiac sign is ' + zodiac + ', which indicates a very sensitive soul.')